# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: news.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='news.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nnews.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n\x0eGetNewsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nstartToken\x18\x02 \x01(\t\"w\n\x05\x45vent\x12 \n\teventType\x18\x01 \x01(\x0e\x32\r.pb.EventType\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"L\n\x0fGetNewsResponse\x12\x19\n\x06\x65vents\x18\x01 \x03(\x0b\x32\t.pb.Event\x12\x11\n\tnextToken\x18\x02 \x01(\t\x12\x0b\n\x03\x65rr\x18\x03 \x01(\t*?\n\tEventType\x12\x0e\n\nLINK_ADDED\x10\x00\x12\x10\n\x0cLINK_UPDATED\x10\x01\x12\x10\n\x0cLINK_DELETED\x10\x02\x32<\n\x04News\x12\x34\n\x07GetNews\x12\x12.pb.GetNewsRequest\x1a\x13.pb.GetNewsResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='pb.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LINK_ADDED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINK_UPDATED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINK_DELETED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=306,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
LINK_ADDED = 0
LINK_UPDATED = 1
LINK_DELETED = 2



_GETNEWSREQUEST = _descriptor.Descriptor(
  name='GetNewsRequest',
  full_name='pb.GetNewsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='pb.GetNewsRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startToken', full_name='pb.GetNewsRequest.startToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=105,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='pb.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventType', full_name='pb.Event.eventType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='pb.Event.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='pb.Event.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pb.Event.timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=226,
)


_GETNEWSRESPONSE = _descriptor.Descriptor(
  name='GetNewsResponse',
  full_name='pb.GetNewsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='pb.GetNewsResponse.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nextToken', full_name='pb.GetNewsResponse.nextToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='pb.GetNewsResponse.err', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=304,
)

_EVENT.fields_by_name['eventType'].enum_type = _EVENTTYPE
_EVENT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETNEWSRESPONSE.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['GetNewsRequest'] = _GETNEWSREQUEST
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['GetNewsResponse'] = _GETNEWSRESPONSE
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetNewsRequest = _reflection.GeneratedProtocolMessageType('GetNewsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETNEWSREQUEST,
  __module__ = 'news_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetNewsRequest)
  ))
_sym_db.RegisterMessage(GetNewsRequest)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'news_pb2'
  # @@protoc_insertion_point(class_scope:pb.Event)
  ))
_sym_db.RegisterMessage(Event)

GetNewsResponse = _reflection.GeneratedProtocolMessageType('GetNewsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNEWSRESPONSE,
  __module__ = 'news_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetNewsResponse)
  ))
_sym_db.RegisterMessage(GetNewsResponse)



_NEWS = _descriptor.ServiceDescriptor(
  name='News',
  full_name='pb.News',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=371,
  serialized_end=431,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNews',
    full_name='pb.News.GetNews',
    index=0,
    containing_service=None,
    input_type=_GETNEWSREQUEST,
    output_type=_GETNEWSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEWS)

DESCRIPTOR.services_by_name['News'] = _NEWS

# @@protoc_insertion_point(module_scope)
