FROM golang:1.11

RUN go get github.com/the-gigi/delinkcious/...

WORKDIR /go/src/github.com/the-gigi/delinkcious/svc/link_service
ADD ./main.go main.go
ADD ./service service

# Fetch dependencies
RUN go get -d -v


RUN CGO_ENABLED=0 GOOS=linux go build -o /link_service -a -tags netgo -ldflags '-s -w' .

EXPOSE 8080
ENTRYPOINT ["/link_service"]
